version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mysite
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: ./entrypoint.sh
    volumes:
      - .:/app
      - backups_data:/backups
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DJANGO_ENV=dev
      - DEBUG=True
      - DB_HOST=postgres
      - DB_NAME=mysite
      - DB_USER=postgres
      - DB_PASS=postgres
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=dev-secret-key-change-in-production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz/"]
      interval: 30s
      timeout: 10s
      retries: 3

  celery:
    build: .
    command: celery -A mysite worker --loglevel=info
    volumes:
      - .:/app
      - backups_data:/backups
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_ENV=dev
      - DEBUG=True
      - DB_HOST=postgres
      - DB_NAME=mysite
      - DB_USER=postgres
      - DB_PASS=postgres
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=dev-secret-key-change-in-production

  celery-beat:
    build: .
    command: celery -A mysite beat --loglevel=info
    volumes:
      - .:/app
      - backups_data:/backups
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_ENV=dev
      - DEBUG=True
      - DB_HOST=postgres
      - DB_NAME=mysite
      - DB_USER=postgres
      - DB_PASS=postgres
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=dev-secret-key-change-in-production

  flower:
    build: .
    command: celery -A mysite flower --basic-auth=${FLOWER_USER:-admin}:${FLOWER_PASS:-admin}
    ports:
      - "5555:5555"
    depends_on:
      - redis
    environment:
      - DJANGO_ENV=dev
      - DEBUG=True
      - DB_HOST=postgres
      - DB_NAME=mysite
      - DB_USER=postgres
      - DB_PASS=postgres
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=dev-secret-key-change-in-production
      - FLOWER_USER=${FLOWER_USER:-admin}
      - FLOWER_PASS=${FLOWER_PASS:-admin}

volumes:
  postgres_data:
  backups_data: