# Generated by Django 5.1.1
from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Populate slug field for existing projects"""
    Project = apps.get_model('portfolio', 'Project')
    for project in Project.objects.all():
        if not project.slug:
            project.slug = slugify(project.title)
            project.save()


class Migration(migrations.Migration):
    dependencies = [
        ('portfolio', '0002_add_mysite_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.RunPython(
            populate_slugs,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
