# Generated by Django 5.0.6 on 2025-09-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_project_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="github_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
