# Generated by Django 5.1.1
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        # No models to create for status app yet
    ]
